<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Converters\" />
    <Folder Include="Helpers\" />
    <Folder Include="Styles\" />
    <Folder Include="Resources\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\Fornecedores\" />
    <Folder Include="Views\Compras\" />
    <Folder Include="Views\Caixa\" />
    <Folder Include="Views\Financeiro\" />
    <Folder Include="Views\Configuracoes\" />
    <Folder Include="Views\Orcamentos\" />
    <Folder Include="Views\Vendas\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConstruSys.Application\ConstruSys.Application.csproj" />
    <ProjectReference Include="..\ConstruSys.Domain\ConstruSys.Domain.csproj" />
    <ProjectReference Include="..\ConstruSys.Infrastructure\ConstruSys.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

</Project>
